### ISSUE TITLE
[Icon request] Steam

### ISSUE THREAD

**Issue by artur9010** [NitruxSA/breeze-icon-theme#343] opened 2016-01-19 12:14 UTC

**Comment by UriHerrera** [comment] 2016-01-19 20:34
Duplicate of: https://github.com/NitruxSA/breeze-icon-theme/issues/278

**Closed by UriHerrera** 2016-01-19 20:34 UTC

**Comment by KAMiKAZOW** [comment] 2016-01-19 20:42
There is no Steam icon in the trademark branch.

**Comment by UriHerrera** [comment] 2016-01-20 00:15
There was one. I don't know why it was deleted: https://gist.github.com/UriHerrera/649aeedcb9468cfeb06a

**Comment by KAMiKAZOW** [comment] 2016-01-20 11:36
Then add it to the trademarks branch again ;)
